### ISSUE TITLE
Update registration info

### ISSUE THREAD

**Issue by soniCaH** [soniCaH/drupalcamp-2015#20]
Check for required fields
Check if all info needed is there

Add "VOLUNTEER" checkbox?

**Comment by soniCaH** [comment]
Nu voorzien:
- Firstname
- Lastname
- Job profile
- Organisation
- Days user attends DrupalCamp
- User wants to volunteer
- Picture
- Bio
- T-shirt Size
- Facebook/Twitter/Linkedin

**Comment by soniCaH** [comment]
If no other fields are required: close Issue

**Comment by soniCaH** [comment]
Added country field in https://github.com/soniCaH/drupalcamp-2015/commit/244ea1b4f7547c060cf51c4fc9e2902e30f60067

**Comment by bramvandenbulcke** [comment]
I did two tests. Both registration e-mails ended up in the spam folder. 

I propose we add a sentence above (or under) the 'Register for DrupalCamp' button with a small text: "In order to complete your registration, an email will be sent to you. If you don't receive the email message directly, please check your spam folder."
